name: marquee

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Npm Install
        run: npm install

      - name: Build
        run: npm run build
      
      - name: Deploy
        uses: peaceiries/actions-gh-pages@v2
        env: 
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
